services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netgross_development
    volumes:
      - netgross_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - netgross-networks

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    networks:
      - netgross-networks

  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    networks:
      - netgross-networks
    tty: true
    stdin_open: true
    env_file:
      - .env
    command: ["/bin/bash", "-c", "rm -f tmp/pids/server.pid && ./docker/development/startup.sh"]

volumes:
  netgross_data:
  bundle:

networks:
  netgross-networks:
    driver: bridge